### ISSUE TITLE
omg module not found

### ISSUE THREAD

**Issue by srama2512** [agiantwhale/NavDoom#3]
I'm getting the following error on running export.sh 
```
Traceback (most recent call last):
  File "wad.py", line 2, in <module>
    from omg import *
ModuleNotFoundError: No module named 'omg'
```

What is the omg package? I can't find any references online or in the README.

**Comment by srama2512** [comment]
Just found it. Need to install the [omgifol](https://github.com/devinacker/omgifol) package.

**Comment by WangChen100** [comment]
Hi srama, how do you solve the error about "name 'WAD' is not defined in line 105 in wad.py "?

When I run wad.py to create wad file, it reminds me such an error. 

Waiting for your reply, thx

**Comment by WangChen100** [comment]
Hi @srama2512 , how do you solve the error about "name 'WAD' is not defined in line 105 in wad.py "?

When I run wad.py to create wad file, it reminds me such an error. 

Waiting for your reply, thx
